repo_url = https://github.com/netty/netty.git
commit_sha = 57bea3bea22717639ba200432c81b23154e4bbd9
module_dir = transport
java = /usr/lib/jvm/java-11-openjdk-amd64
mvnopts = -Djacoco.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true -Dlicense.skip=true -Dcheckstyle.skip -Denforcer.skip=true -Dspotbugs.skip=true -Dfindbugs.skip=true -Ddependency-check.skip=true -Dmaven.test.failure.ignore=true -Dhawtjni.skip=true -Drevapi.skip=true -Djapicmp.skip=true -Dgpg.skip=true -DfailIfNoTests=false -fn -Dsurefire.security.manager=true
