repo_url = https://github.com/snakeyaml/snakeyaml.git
commit_sha = e6eb1b7274ea42aceb4194b56392ab42954e1120
module_dir = .
java = /usr/lib/jvm/java-8-openjdk-amd64
mvnopts = -Djacoco.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true -Dlicense.skip=true -Dcheckstyle.skip -Denforcer.skip=true -Dspotbugs.skip=true -Dfindbugs.skip=true -Ddependency-check.skip=true -Dmaven.test.failure.ignore=true -Dhawtjni.skip=true -Drevapi.skip=true -Djapicmp.skip=true -Dgpg.skip=true -DfailIfNoTests=false -fn
